"""
Pydantic Structured Output Schemas for SENTINEL Text Analysis.
==============================================================
These schemas define the contract for the single-pass multi-task LLM call.
Used with `model.with_structured_output(SentinelTextAnalysis)` to enforce
typed, validated responses from the LangChain pipeline.
"""

from enum import Enum
from typing import List
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Task 1: AI Generation Detection
# ---------------------------------------------------------------------------

class StyleMarker(str, Enum):
    """Stylometric markers indicative of AI-generated text."""
    LOW_PERPLEXITY = "low_perplexity"
    MONOTONOUS_RHYTHM = "monotonous_rhythm"
    LLM_BOILERPLATE = "llm_boilerplate"
    EXCESSIVE_HEDGING = "excessive_hedging"
    UNIFORM_SENTENCE_LENGTH = "uniform_sentence_length"
    LACK_OF_TYPOS = "lack_of_typos"
    REPETITIVE_TRANSITIONS = "repetitive_transitions"


class AIGenerationDetection(BaseModel):
    """Assessment of whether the text was generated by an AI language model."""

    is_ai_generated: bool = Field(
        description="True if the text is likely AI-generated, False if likely human-written."
    )
    confidence_score: int = Field(
        ge=0,
        le=100,
        description="Confidence in the AI generation assessment (0=no confidence, 100=certain).",
    )
    detected_markers: List[StyleMarker] = Field(
        default_factory=list,
        description="List of stylometric markers that indicate AI authorship.",
    )
    reasoning: str = Field(
        description="Brief explanation of the detection rationale."
    )


# ---------------------------------------------------------------------------
# Task 2: Harm & Safety Assessment
# ---------------------------------------------------------------------------

class RiskLevel(str, Enum):
    """Categorical risk classification."""
    SAFE = "SAFE"           # 0-20
    LOW = "LOW"             # 21-40
    MODERATE = "MODERATE"   # 41-60
    HIGH = "HIGH"           # 61-80
    CRITICAL = "CRITICAL"   # 81-100


class HarmCategory(str, Enum):
    """Categories of harmful content to evaluate."""
    HATE_SPEECH = "Hate Speech"
    HARASSMENT = "Harassment & Bullying"
    VIOLENCE = "Violence & Graphic Content"
    SEXUAL_NSFW = "Sexual / NSFW Content"
    MISINFORMATION = "Misinformation"
    POLITICAL_BIAS = "Political Bias / Propaganda"
    SCAM_FRAUD = "Scam / Fraud / Phishing"
    SELF_HARM = "Self-Harm / Suicide"
    EXTREMISM = "Extremism / Terrorism"
    PROFANITY_TOXIC = "Profanity / Toxic Language"


class HarmSafetyAssessment(BaseModel):
    """Safety evaluation of the text across multiple harm dimensions."""

    risk_score: int = Field(
        ge=0,
        le=100,
        description="Overall risk score (0=perfectly safe, 100=critically dangerous).",
    )
    risk_level: RiskLevel = Field(
        description="Categorical risk classification derived from the risk score."
    )
    flagged_categories: List[HarmCategory] = Field(
        default_factory=list,
        description="List of harm categories that were detected in the text.",
    )
    summary: str = Field(
        description="Brief explanation of identified risks."
    )


# ---------------------------------------------------------------------------
# Task 3: Domain Classification
# ---------------------------------------------------------------------------

class DomainTopic(str, Enum):
    """Primary domain/topic categories for text classification."""
    POLITICS = "politics"
    TECHNOLOGY = "technology"
    FINANCE = "finance"
    HEALTH = "health"
    SCIENCE = "science"
    SPORTS = "sports"
    ENTERTAINMENT = "entertainment"
    EDUCATION = "education"
    ENVIRONMENT = "environment"
    CRIME = "crime"
    OTHER = "other"


class DomainClassification(BaseModel):
    """Topic and domain classification of the text content."""

    primary_topic: DomainTopic = Field(
        description="The single most relevant domain/topic category."
    )
    sub_topics: List[str] = Field(
        min_length=2,
        max_length=3,
        description=(
            "2-3 specific sub-topic tags within the primary domain "
            "(e.g., ['cybersecurity', 'data privacy'])."
        ),
    )


# ---------------------------------------------------------------------------
# Root Schema: Single-Pass Composite
# ---------------------------------------------------------------------------

class SentinelTextAnalysis(BaseModel):
    """
    Root schema for the SENTINEL Single-Pass Multi-Task text analysis.

    This is the structured output target for the LangChain call.
    All three analysis tasks are executed in a single LLM invocation.
    """

    ai_detection: AIGenerationDetection = Field(
        description="AI generation detection results."
    )
    safety: HarmSafetyAssessment = Field(
        description="Harm and safety assessment results."
    )
    domain: DomainClassification = Field(
        description="Domain and topic classification results."
    )
